In [1]:
import pandas as pd

In [2]:
import sklearn
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split  # 알아서 학습

In [ ]:
import pandas as pd

iris = load_iris()

iris_data = iris.data # 피처 : 꽃바침의 너비 길이, 꽃잎의 너비 길이
iris_label = iris.target # 아이리스 품종 : 정답

print('iris target값 :', iris_label)
print('iris target명 :', iris.target_names)

iris target값 : [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target명 : ['setosa' 'versicolor' 'virginica']

In [ ]:
iris_df = pd.DataFrame(data= iris_data, columns= iris.feature_names)
iris_df['label'] = iris.target      # 레이블/타깃(label) : 맞히려는 정답 보통 y로 표기
iris_df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [ ]:
# 학습셋과 테스트셋으로 나누기
# train 학습 test 
X_train, X_test, Y_train, Y_test = train_test_split(iris_data, iris_label, test_size=0.2, random_state=39) # random_state 고정 시 매번 방식 같음
# test 크기 0.2 -> train 크기 0.8

In [ ]:
dt_clf = DecisionTreeClassifier(random_state=39) # 분류기

In [ ]:
dt_clf.fit(X_train, Y_train) # fit() - 학습시키기

DecisionTreeClassifier(random_state=39)

In [ ]:
pred = dt_clf.predict(X_test) # predict() - 예측
pred

array([0, 0, 2, 1, 0, 0, 2, 0, 2, 2, 1, 0, 2, 1, 1, 1, 2, 2, 2, 0, 2, 0,
       0, 1, 1, 0, 1, 1, 2, 1])

In [ ]:
from sklearn.metrics import accuracy_score
print('예측 정확도 :', accuracy_score(Y_test, pred)) # 정확도 1 일시 잘못된 코드

예측 정확도 : 0.9666666666666667

In [ ]:
from sklearn.model_selection import KFold # model_selection - 데이터 분리, 교차 검증 시 사용
import numpy as np                        # K-Fold란? 데이터를 k 조각 나눠 돌아가며 시험 - 교차 검증

kfold = KFold(n_splits= 5)
cv_accuracy = []

In [ ]:
n_iter = 0
features = iris.data
label = iris.target

for train_index, test_index in kfold.split(features) : # kfold로 나눈만큼 반복
    X_train, X_test = features[train_index], features[test_index]
    Y_train, Y_test = label[train_index], label[test_index]

    dt_clf.fit(X_train, Y_train)
    pred = dt_clf.predict(X_test)
    n_iter += 1

    accuracy = np.round(accuracy_score(Y_test, pred), 4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]

    print(n_iter)
    print('교차검증 정확도 :', accuracy)
    print('학습 데이터 크기 :', train_size)
    print('검증 데이터 크기 :', test_size)
    cv_accuracy.append(accuracy)

print('평균 검증 정확도 : ', np.mean(cv_accuracy))

1
교차검증 정확도 : 1.0
학습 데이터 크기 : 120
검증 데이터 크기 : 30
2
교차검증 정확도 : 0.9667
학습 데이터 크기 : 120
검증 데이터 크기 : 30
3
교차검증 정확도 : 0.8333
학습 데이터 크기 : 120
검증 데이터 크기 : 30
4
교차검증 정확도 : 0.9333
학습 데이터 크기 : 120
검증 데이터 크기 : 30
5
교차검증 정확도 : 0.8
학습 데이터 크기 : 120
검증 데이터 크기 : 30
평균 검증 정확도 :  0.9066599999999999

In [24]:
iris_df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [25]:
iris_df['label'].value_counts()

0    50
1    50
2    50
Name: label, dtype: int64

In [26]:
kfold = KFold(n_splits= 3)

for train_index, test_index in kfold.split(iris_df):
    
    n_iter += 1
    
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]

    print('학습 레이블 데이터 분포 :', label_train.value_counts())
    print('검증 레이블 데이터 분포 :', label_test.value_counts())

학습 레이블 데이터 분포 : 1    50
2    50
Name: label, dtype: int64
검증 레이블 데이터 분포 : 0    50
Name: label, dtype: int64
학습 레이블 데이터 분포 : 0    50
2    50
Name: label, dtype: int64
검증 레이블 데이터 분포 : 1    50
Name: label, dtype: int64
학습 레이블 데이터 분포 : 0    50
1    50
Name: label, dtype: int64
검증 레이블 데이터 분포 : 2    50
Name: label, dtype: int64

In [ ]:
from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits = 3)
n_iter = 0

for train_index, test_index in skf.split(iris_df, iris_df['label']) :
    n_iter += 1

    label_train = iris_df['label'].iloc[train_index] # 학습용 레이블
    label_test = iris_df['label'].iloc[test_index] # 검증용 레이블

    print('학습 레이블 데이터 분포 :', label_train.value_counts())
    print('검증 레이블 데이터 분포 :', label_test.value_counts())

학습 레이블 데이터 분포 : 2    34
0    33
1    33
Name: label, dtype: int64
검증 레이블 데이터 분포 : 0    17
1    17
2    16
Name: label, dtype: int64
학습 레이블 데이터 분포 : 1    34
0    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포 : 0    17
2    17
1    16
Name: label, dtype: int64
학습 레이블 데이터 분포 : 0    34
1    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포 : 1    17
2    17
0    16
Name: label, dtype: int64

In [ ]:
dt_clf = DecisionTreeClassifier(random_state= 156)
skfold = StratifiedKFold(n_splits=3)
n_iter = 0
cv_accuracy = [] # 각 fold별 정확도 저장할 리스트

for train_index, test_index in skfold.split(features, label):
    X_train, X_test = features[train_index], features[test_index] # 학습/검증용 분리
    Y_train, Y_test = label[train_index], label[test_index] # 학습/검증용 분리

    dt_clf.fit(X_train, Y_train)
    pred = dt_clf.predict(X_test) 

    n_iter += 1
    accuracy = np.round(accuracy_score(Y_test, pred), 4) # 정확도 소수점 4번째까지 출력
    cv_accuracy.append(accuracy)

print('평균 검증 정확도 :', np.round(np.mean(cv_accuracy), 4))

평균 검증 정확도 : 0.9667

In [ ]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(dt_clf, features, label, scoring='accuracy', cv = 3)

print('교차 검증 정확도 :', np.round(scores, 4))
print('평균 검증 정확도 :', np.round(np.mean(scores), 4))

교차 검증 정확도 : [0.98 0.94 0.98]
평균 검증 정확도 : 0.9667

In [31]:
# gridsearchcv 하이퍼파라미터 최적화 도구

from sklearn.model_selection import GridSearchCV

X_train, X_test, Y_train, Y_test = train_test_split(iris.data, iris.target, test_size=0.2, random_state= 121)

parameters = {'max_depth' : [1, 2, 3], 'min_samples_split': [2, 3]}

In [32]:
dtree = DecisionTreeClassifier()

grid_dtree = GridSearchCV(dtree, param_grid= parameters, cv=3, refit=True)

grid_dtree.fit(X_train, Y_train)
scores_df = pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params', 'mean_test_score', 'rank_test_score', 'split0_test_score', 'split1_test_score', 'split2_test_score']]

,params,mean_test_score,rank_test_score,split0_test_score,split1_test_score,split2_test_score
0,"{'max_depth': 1, 'min_samples_split': 2}",0.700000,5,0.700,0.7,0.70
1,"{'max_depth': 1, 'min_samples_split': 3}",0.700000,5,0.700,0.7,0.70
2,"{'max_depth': 2, 'min_samples_split': 2}",0.958333,3,0.925,1.0,0.95
3,"{'max_depth': 2, 'min_samples_split': 3}",0.958333,3,0.925,1.0,0.95
4,"{'max_depth': 3, 'min_samples_split': 2}",0.975000,1,0.975,1.0,0.95
5,"{'max_depth': 3, 'min_samples_split': 3}",0.975000,1,0.975,1.0,0.95

In [ ]:
grid_dtree.best_params_ # 최고의 방법?

{'max_depth': 3, 'min_samples_split': 2}

In [ ]:
grid_dtree.best_score_ # 위 최고의 방법으로 찾을 시 점수

0.975

In [35]:
estimator = grid_dtree.best_estimator_

pred = estimator.predict(X_test)
print(accuracy_score(Y_test, pred))

0.9666666666666667

In [ ]:
from sklearn.preprocessing import LabelEncoder  # 컴퓨터가 처리하기 쉽게 변환 ex) 서울 - 1 부산 - 2 

items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print(labels)

[0 1 4 5 3 3 2 2]

In [38]:
encoder.classes_

array(['TV', '냉장고', '믹서', '선풍기', '전자레인지', '컴퓨터'], dtype='<U5')

In [ ]:
from sklearn.preprocessing import OneHotEncoder  
import numpy as np

items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

items = np.array(items).reshape(-1, 1)

items

array([['TV'],
       ['냉장고'],
       ['전자레인지'],
       ['컴퓨터'],
       ['선풍기'],
       ['선풍기'],
       ['믹서'],
       ['믹서']], dtype='<U5')

In [ ]:
oh_encoder = OneHotEncoder() # 칼럼명 바꿈 가전제품 -> 가전제품_TV  칼럼명이 열에  해당하면 1아니면 0
oh_encoder.fit(items)
oh_labels = oh_encoder.transform(items)

print(oh_labels.toarray())
print(oh_labels.shape)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
(8, 6)

In [41]:
df = pd.DataFrame({'items' : ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']})

In [42]:
pd.get_dummies(df)

   items_TV  items_냉장고  items_믹서  items_선풍기  items_전자레인지  items_컴퓨터
0         1          0         0          0            0          0
1         0          1         0          0            0          0
2         0          0         0          0            1          0
3         0          0         0          0            0          1
4         0          0         0          1            0          0
5         0          0         0          1            0          0
6         0          0         1          0            0          0
7         0          0         1          0            0          0

In [ ]:
from sklearn.datasets import load_iris

iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns= iris.feature_names)

print(iris_df.mean()) # 평균
print(iris_df.var()) # 분산

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64

In [ ]:
# StandardScaler

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

iris_df_scaled = pd.DataFrame(data = iris_scaled, columns = iris.feature_names)

print(iris_df_scaled.mean())
print(iris_df_scaled.var())

sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64

In [46]:
# MinMaxScaler

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

iris_df_scaled = pd.DataFrame(data= iris_scaled, columns= iris.feature_names)
print(iris_df_scaled.min())
print(iris_df_scaled.max())

sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64

In [ ]:
# transform은 둘 다
# fit은 train 데이터에만 테스트 데이터엔 x